### ISSUE TITLE
verse19 test

### ISSUE THREAD

**Issue by genius-7** [AlexYouXin/PnPNet#4]
想请问一下，为什么我在verse19上面测试效果非常差，训练过程中验证集dice也都比较高。

**Comment by AlexYouXin** [comment]
For a patch-based paradigm, the patch-cropping strategy is important, especially for the vertebral sequential structure. Maybe it will work by adopting the center cropping strategy for the whole CT scan.

**Comment by genius-7** [comment]
我是按照你所提供的test.py和utils.py进行test的，请问你对于verse19这个数据集进行测试时有什么修改吗，我看你的文章中各项指标都不错

**Comment by AlexYouXin** [comment]
没有额外修改了，可以邮件发我看下你的training log

**Comment by genius-7** [comment]
我该发到哪个邮箱呢，麻烦你提供一下邮箱，谢谢

**Comment by AlexYouXin** [comment]
> 我该发到哪个邮箱呢，麻烦你提供一下邮箱，谢谢

sjtu_youxin@sjtu.edu.cn

**Comment by genius-7** [comment]
您好，我给您发了邮件，您收到了吗，麻烦您抽空可以帮我看一看，谢谢

**Comment by AlexYouXin** [comment]
> 您好，我给您发了邮件，您收到了吗，麻烦您抽空可以帮我看一看，谢谢

已给予反馈，希望能解决你的问题！

**Comment by AlexYouXin** [comment]
Given files of trainer.py & utils.py are coded for lung lobe datasets. Those files should be modified to fit the vertebral anatomical structure.

**Comment by genius-7** [comment]
Hello, I received your feedback. My weight settings during training were set according to [0.25] + [0.75] * 25, but I am still not sure about the settings of utils.py of the verse19 data set. Can you share the utils.py of verse19? Thank you

**Comment by AlexYouXin** [comment]
> Hello, I received your feedback. My weight settings during training were set according to [0.25] + [0.75] * 25, but I am still not sure about the settings of utils.py of the verse19 data set. Can you share the utils.py of verse19? Thank you

Please refer to https://github.com/AlexYouXin/Explicit-Shape-Priors/blob/main/utils/VerSe_utils.py

**Comment by genius-7** [comment]
Thanks for your help, I'll try it again.
