### ISSUE TITLE
Request for Access to SLoRD Model for Academic Research?

### ISSUE THREAD

**Issue by HaoyuCao** [AlexYouXin/PnPNet#7]
I am currently pursuing my Master's degree in medical image segmentation via deep learning based method. I recently read your paper titled "SLoRD: Structural Low-Rank Descriptors for Shape Consistency in Vertebrae Segmentation" on arXiv and found your work to be highly inspiring. I am very interested in reproducing the SLoRD model to compare it with my current research.

However, I noticed that the GitHub link provided in the arXiv paper and on your personal homepage appears to be inactive, and it seems the SLoRD project has been removed. 

I would like to kindly inquire if you would be willing to make the SLoRD model available again. I assure you that the model will be used solely for academic research purposes and not for any other uses.
![404](https://github.com/user-attachments/assets/2103690e-4875-404c-8c7d-1bbafcceff3d)

**Comment by AlexYouXin** [comment]
Thank you so much for your attention on our work. The framework of SLoRD is still in progress, and we will make the github project available in the near future.
